name: jest-unit-testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm install
      - name: unit testing
        run: npm test
